export const AUTH = {
  user: "api/v1/User",
  userByBusiness: "api/v1/User/by-business",
  additionalUser: "api/v1/User/additional-account",
  generateToken: "api/v1/OneTimePassword/generate",
  validateToken: "api/v1/OneTimePassword/validate",
  registerBusiness: "api/v1/business",
  loginUser: "api/v1/User/login",
  loginUserSelectedBusiness: "api/v1/User/login-selected-business",
  refreshToken: "api/v1/User/refresh-token",
  forgetPassword: "api/v1/User/forget-password",
  changePassword: "api/v1/User/change-password",
  getBusiness: "api/v1/Business/configuration",
  getRoleCount: "api/v1/User/role-count",
  logout: "api/v1/User/logout",
};
export const LANDINGPAGE = {
  getFAQs: "api/v1/LandingPage/faqs",
  addToWaitList: "api/v1/LandingPage/waitlist",
  getPricing: "api/v1/LandingPage/pricing",
  getCompanies: "api/v1/LandingPage/registered-business-logo",
  contactUs: "api/v1/LandingPage/contact",
  bookDemo: "api/v1/LandingPage/book-demo",
  getNews: "api/v1/LandingPage/news",
  getCampaigns: "api/v1/LandingPage/campaigns",
  getReservations: "api/v1/LandingPage/reservations",
  bookReservation: "api/v1/Booking",
  reservationAvailility: "api/v1/Reservation/availability",
};
export const DASHBOARD = {
  // settings
  getRoleByBusiness: "api/v1/User/role-by-business",
  configureRole: "api/v1/User/role-configure",
  termAndCondition: "api/v1/TermAndCondition",
  getTermAndCondition: "api/v1/TermAndCondition/by-business",
  notificationCount: "api/v1/Notification/UnReadCount",
  notifications: "api/v1/Notification/by-business",
  markAsRead: "api/v1/Notification/MarkAsRead",
  markAllAsRead: "api/v1/Notification/MarkAllAsRead",
  getBusiness: "api/v1/Business",
  getBusinessByCooperate: "api/v1/Business/by-cooperate",
  getFile: "api/v1/File/retrieve",
  // menu
  getMenu: "api/v1/Menu",
  menuConfiguration: "api/v1/Menu/configuration",
  getMenuByBusiness: "api/v1/Menu/by-business",
  menuByUserBusiness: "api/v1/Menu/by-business-user",
  menuItem: "api/v1/Menu/item",
  uploadFile: "api/v1/File/upload",
  removeFile: "api/v1/File/remove",
  uploadBulkMenuItem: "api/v1/Menu/item-upload",
  menuVariety: "api/v1/Menu/item-variety",
  menuCategories: "api/v1/Menu/categories",
  menuCategory: "api/v1/Menu/category",
  menuItems: "api/v1/Menu/items",
  menuPos: "api/v1/Menu/pos",
  // orders
  orderByBusiness: "api/v1/Order/by-business",
  orderByCategories: "/api/v1/Order/categories",
  orderItems: "api/v1/Order/details",
  orderByPaged: "api/v1/Order/paged",
  orderByReference: "api/v1/Order/by-reference",
  order: "api/v1/Order",
  orderByRef: "api/v1/Order/by-reference",
  placeOrder: "api/v1/Order/place",
  completeOrder: "api/v1/Order/mark-complete",
  completeOrderWithPayment: "api/v1/Order/payment",
  paymentSummary: "api/v1/Order/payment",
  refundOrder: "api/v1/Order/refund",
  cancelOrder: "api/v1/Order/cancel",

  // Payments
  paymentByBusiness: "api/v1/Payment/categories",
  paymentByDetail: "api/v1/Payment/details",
  confirmPayment: "api/v1/Payment/confirm",
  // Quick response
  qrByBusiness: "api/v1/QuickResponse/detail-by-business",
  qrAllBy: "api/v1/QuickResponse/by-business",
  qr: "api/v1/QuickResponse",
  // Reservations
  reservationsByBusiness: "api/v1/Reservation/by-business",
  reservationsByBusinessUser: "api/v1/Reservation/by-business-user",
  reservation: "api/v1/Reservation",
  singleReservation: "api/v1/Reservation/fetch",
  singleBookings: "api/v1/Reservation/by-id",
  // Bookings
  bookings: "api/v1/Booking",
  bookingsByBusiness: "api/v1/Booking/categories",
  bookingsByDetails: "api/v1/Booking/details",
  bookingsByRef: "api/v1/Booking/by-ref",
  updateStatus: "api/v1/Booking/update-status",
  //Campaigns
  // campaignsByBusiness: "api/v1/Campaign/by-business",
  campaignsByCategories: "api/v1/Campaign/categories",
  campaignByCategory: "api/v1/Campaign/details",
  campaigns: "api/v1/Campaign",
  repeatCampaigns: "api/v1/Campaign/restart",
  //Dashboard
  dashboard: "api/v1/DashboardReportManager",
  //Report
  report: "api/v1/ReportManager",
  reportOrder: "api/v1/ReportManager/order",
  reportOrderExport: "api/v1/ReportManager/order/export",
  reportBookingExport: "api/v1/ReportManager/booking/export",
  reportAuditLogExport: "api/v1/ReportManager/user/export",
  reportPaymentExport: "api/v1/ReportManager/payment/export",
  reportGridExport: "api/v1/ReportManager/grid/export",
  reportPayment: "api/v1/ReportManager/payment",
  reportBooking: "api/v1/ReportManager/booking",
  reportAuditLog: "api/v1/ReportManager/user",
  //Billings and Subscriptions
  subscription: "api/v1/Subscription",
  userSubscription: "api/v1/Subscription/User",
  manage: "api/v1/Subscription/manaage-url",
  intializeTransaction: "api/v1/Transaction/initialise",
  completeTransaction: "api/v1/Transaction/complete",
  // Inventory
  unit: "api/v1/Unit",
  inventory: "api/v1/Inventory",
  inventoryByBusiness: "api/v1/Inventory/by-business",
  inventoryItems: "api/v1/Inventory/items",
  inventoryItem: "api/v1/Inventory/item",
  inventoryCategories: "api/v1/Inventory/categories",
  inventoryItemUnit: "api/v1/Inventory/item-unit",
  inventoryRecipe: "api/v1/Inventory/recipe",
  inventoryRecipeByBusiness: "api/v1/Inventory/recipe/by-business",
  inventoryRecipeDetails: "api/v1/Inventory/recipe/details",
  inventoryRecipeByItem: "api/v1/Inventory/recipe/by-item",
  inventoryRecipeProduceBatch: "api/v1/Inventory/recipe/produce-batch",
  inventoryBatchProduction: "api/v1/Inventory/batch-production",
  supplier: "api/v1/Supplier",
  supplierByBusiness: "api/v1/Supplier/by-business",
  mapSupplierItem: "api/v1/Supplier/map-item",
  // Purchase Order
  purchaseOrder: "api/v1/PurchaseOrder",
  purchaseOrderByBusiness: "api/v1/PurchaseOrder/by-business",
  purchaseOrderReceive: "api/v1/PurchaseOrder/receive",
  purchaseOrderSendMail: "api/v1/PurchaseOrder/send-mail",
  // Inventory Wizard
  inventoryWizardMenuSummary: "api/v1/InventoryWizard/menu-summary",
  inventoryWizardPredict: "api/v1/InventoryWizard/predict",
  inventoryWizardSynchronize: "api/v1/InventoryWizard/synchronize",
  inventoryWizardSetup: "api/v1/InventoryWizard/setup",
};

export const INVENTORY = {
  inventoryByBusiness: "api/v1/Inventory/by-business",
  unitByBusiness: "api/v1/Unit/by-business",
  unit: "api/v1/Unit",
};
