import { Supplier } from "./types";

export const mockSuppliers: Supplier[] = [
  {
    id: "1",
    supplierId: "454121V",
    name: "Sandra Okoranikwo",
    companyName: "D'Arena Store",
    email: "darenastore@gmail.com",
    address: "1 Adeguwa Street, Yaba",
    phoneNumber: "09012345678",
    status: "active",
    items: [
      { id: "101", name: "Golden Penny Spaghetti" },
      { id: "102", name: "Vegetable Oil" },
    ],
  },
  {
    id: "2",
    supplierId: "454121V",
    name: "Seun Obafemi",
    companyName: "Trolleys",
    email: "trollexyang@gmail.com",
    address: "53 Queens Street, Yaba",
    phoneNumber: "09012345678",
    status: "active",
    items: [{ id: "201", name: "Salt" }],
  },
  {
    id: "3",
    supplierId: "454121V",
    name: "Rachel Laurence",
    companyName: "Mall Mart",
    email: "mallmartyaba@gmail.com",
    address: "123 Herbert Macaulay Way, Sabo Yaba, Lagos",
    phoneNumber: "09012345678",
    status: "active",
    items: [
      { id: "301", name: "Golden Penny Spaghetti" },
      { id: "302", name: "Vegetable Oil" },
      { id: "303", name: "Salt" },
      { id: "304", name: "Gino Tomato Paste" },
      { id: "305", name: "Bell Peppers" },
      { id: "306", name: "Carrots" },
      { id: "307", name: "Maggi Seasoning Cubes" },
    ],
  },
  {
    id: "4",
    supplierId: "454121V",
    name: "Bunmi Susan",
    companyName: "Bokku",
    email: "bokkuyaba@gmail.com",
    address: "132 Herbert Macaulay Way",
    phoneNumber: "09012345678",
    status: "active",
    items: [],
  },
  {
    id: "5",
    supplierId: "454121V",
    name: "Mark Osu",
    companyName: "Ozone Mall",
    email: "ozonemall@gmail.com",
    address: "65 Industrial Avenue, Sabo",
    phoneNumber: "08012345678",
    status: "active",
    items: [],
  },
  {
    id: "6",
    supplierId: "454121V",
    name: "Ope Falana",
    companyName: "Ope Store",
    email: "opefalana@gmail.com",
    address: "10 Murtala Mohammed Way",
    phoneNumber: "09012345678",
    status: "active",
    items: [],
  },
];
